// Source content for the seed script. Edit here (or in the Supabase dashboard
// after seeding) to add more years / questions.
import { UGCNET_DEC2025 } from "./seed-ugcnet-dec2025";

export type SeedQuestion = {
  topic: string;
  question: string;
  options: string[];
  answer_index: number;
  explanation: string;
};

// ---- Previous Year Questions, grouped by exam session ----
export const PYQ: Record<string, SeedQuestion[]> = {
  "June 2023": [
    { topic: "Teaching", question: "Which of the following is NOT a characteristic of effective teaching?", options: ["Clarity of content presentation", "Emphasis on rote memorization", "Active learner engagement", "Use of relevant examples"], answer_index: 1, explanation: "Effective teaching promotes understanding and critical thinking, not rote memorization." },
    { topic: "Teaching", question: "The term 'pedagogy' refers to:", options: ["The science of adult learning", "The art and science of teaching", "The study of child development", "The philosophy of education"], answer_index: 1, explanation: "Pedagogy is the art and science of teaching, particularly strategies and methods used to impart knowledge." },
    { topic: "Research", question: "A researcher formulates a hypothesis before conducting an experiment. This is best described as:", options: ["A proven fact derived from data", "A testable prediction or assumption", "A conclusion drawn from findings", "A statistical analysis result"], answer_index: 1, explanation: "A hypothesis is a tentative, testable statement or prediction that guides research inquiry." },
    { topic: "Research", question: "Which type of research is aimed at solving specific practical problems?", options: ["Pure / Fundamental research", "Applied research", "Historical research", "Philosophical research"], answer_index: 1, explanation: "Applied research is conducted to solve specific, real-world problems." },
    { topic: "Communication", question: "In the communication process, 'noise' refers to:", options: ["The loudness of the message", "Any disturbance that interferes with communication", "The feedback from the receiver", "The encoding of the message"], answer_index: 1, explanation: "Noise is any internal or external interference that disrupts or distorts the communication process." },
    { topic: "Reasoning", question: "If TEACHER is coded as VGCEJGT, how is STUDENT coded?", options: ["UVWFGPV", "UVWEGPV", "UVWFGOV", "UUWFGPV"], answer_index: 0, explanation: "Each letter shifts +2: S→U, T→V, U→W, D→F, E→G, N→P, T→V → UVWFGPV." },
    { topic: "Education", question: "The National Education Policy 2020 recommends the medium of instruction up to Grade 5 should preferably be:", options: ["English", "Hindi", "Home language / mother tongue", "Regional official language"], answer_index: 2, explanation: "NEP 2020 recommends mother tongue or home language as the medium of instruction up to at least Grade 5." },
    { topic: "Environment", question: "Which of the following is a renewable source of energy?", options: ["Coal", "Petroleum", "Solar energy", "Natural gas"], answer_index: 2, explanation: "Solar energy is renewable — it comes from the Sun, an inexhaustible source." },
    { topic: "Data Interpretation", question: "A pie chart is best used to show:", options: ["Trends over time", "Frequency distribution", "Proportion of parts to the whole", "Correlation between variables"], answer_index: 2, explanation: "A pie chart shows how parts contribute proportionally to a whole." },
    { topic: "Research", question: "Which of the following is an example of a secondary source of information?", options: ["Original research articles", "Laboratory experiment reports", "Review articles and textbooks", "First-hand field observations"], answer_index: 2, explanation: "Secondary sources summarise or analyse primary data — textbooks and review articles are classic examples." },
  ],
  "December 2022": [
    { topic: "Teaching", question: "The teaching method that best promotes critical thinking and problem-solving is:", options: ["Lecture method", "Demonstration method", "Problem-based learning", "Drill and practice"], answer_index: 2, explanation: "Problem-based learning engages students in solving real-world problems, developing critical thinking." },
    { topic: "Research", question: "Which of the following is NOT a method of data collection?", options: ["Observation", "Interview", "Hypothesis testing", "Questionnaire"], answer_index: 2, explanation: "Hypothesis testing is analysis, not collection. Observation, interview, and questionnaire are collection methods." },
    { topic: "Teaching", question: "'Bloom's Taxonomy' classifies:", options: ["Classroom management strategies", "Levels of cognitive learning objectives", "Educational psychology disorders", "Curriculum planning frameworks"], answer_index: 1, explanation: "Bloom's Taxonomy (1956) classifies educational objectives into six cognitive levels: Remember, Understand, Apply, Analyse, Evaluate, Create." },
    { topic: "Environment", question: "Which greenhouse gas has the highest global warming potential (100-year)?", options: ["Carbon dioxide (CO₂)", "Methane (CH₄)", "Nitrous oxide (N₂O)", "Water vapour"], answer_index: 1, explanation: "Methane's global warming potential is about 25× that of CO₂ over a 100-year period." },
    { topic: "Reasoning", question: "In a code, 'MIND' is written as 'NKPF'. How is 'BOOK' written?", options: ["DQQM", "CPQL", "BPPK", "CQQL"], answer_index: 0, explanation: "Each letter shifts +2: B→D, O→Q, O→Q, K→M → DQQM." },
    { topic: "Teaching", question: "Which correctly describes formative assessment?", options: ["Assessment at the end of a unit", "Ongoing assessment during learning to guide instruction", "A standardised national exam", "Assessment for certification only"], answer_index: 1, explanation: "Formative assessment is continuous, used during the learning process to monitor progress and provide feedback." },
    { topic: "ICT", question: "The full form of 'ICT' in education is:", options: ["International Communication Technology", "Information and Communication Technology", "Integrated Classroom Teaching", "Instructional Content Transfer"], answer_index: 1, explanation: "ICT stands for Information and Communication Technology." },
    { topic: "Education", question: "Which organisation accredits higher education institutions in India?", options: ["UGC", "NAAC", "AICTE", "NCERT"], answer_index: 1, explanation: "NAAC (National Assessment and Accreditation Council), established in 1994, accredits Higher Education Institutions in India." },
    { topic: "Reasoning", question: "Deductive reasoning proceeds from:", options: ["Specific observations to general conclusions", "General principles to specific conclusions", "Data to hypothesis", "Experiment to theory"], answer_index: 1, explanation: "Deductive reasoning moves from general principles (premises) to specific conclusions." },
    { topic: "Data Interpretation", question: "Which chart type is most suitable for showing a variable's trend over time?", options: ["Bar chart", "Pie chart", "Line chart", "Histogram"], answer_index: 2, explanation: "Line charts are best for displaying how a variable changes over continuous time." },
  ],
  "June 2022": [
    { topic: "Education", question: "Which is a key feature of distance education?", options: ["Mandatory face-to-face interaction", "Fixed classroom schedule", "Self-paced learning with flexible timing", "Limited to rural areas"], answer_index: 2, explanation: "Distance education allows learners to study at their own pace without mandatory physical attendance." },
    { topic: "Research", question: "A longitudinal research study:", options: ["Studies multiple variables at one point in time", "Follows the same subjects over an extended period", "Compares two different groups simultaneously", "Uses historical data only"], answer_index: 1, explanation: "Longitudinal research tracks the same subjects over time to observe changes and developments." },
    { topic: "Communication", question: "The 'grapevine' in communication refers to:", options: ["Formal organisational channels", "Official written correspondence", "Informal, unofficial communication network", "Communication via electronic media"], answer_index: 2, explanation: "Grapevine refers to the informal communication network within an organisation, spreading through unofficial channels." },
    { topic: "Education", question: "In which year was the UGC established?", options: ["1948", "1953", "1956", "1961"], answer_index: 1, explanation: "The UGC was established in 1953 by the Government of India to coordinate and maintain standards of higher education." },
    { topic: "Reasoning", question: "All roses are flowers. Some flowers fade quickly. What is a valid conclusion?", options: ["All roses fade quickly", "Some roses fade quickly", "No roses fade quickly", "None of the above can be definitely concluded"], answer_index: 3, explanation: "We know all roses are flowers but only some flowers fade quickly — we cannot determine which flowers fade quickly, so none of A, B, or C can be definitively concluded." },
    { topic: "ICT", question: "The 'digital divide' refers to:", options: ["Gap between hardware and software", "Inequality in access to digital technology", "Difference between analog and digital signals", "Space between digital characters"], answer_index: 1, explanation: "The digital divide is the gap between those who have access to modern information technology and those who do not." },
    { topic: "Research", question: "Which is a primary source of data?", options: ["Published research reports", "Encyclopaedias", "Questionnaire survey by the researcher", "Newspaper articles"], answer_index: 2, explanation: "A questionnaire survey conducted by the researcher collects first-hand (primary) data directly from respondents." },
    { topic: "Environment", question: "The Montreal Protocol (1987) was designed to address:", options: ["Global warming due to CO₂", "Depletion of the ozone layer by CFCs", "Ocean acidification", "Deforestation and land degradation"], answer_index: 1, explanation: "The Montreal Protocol is an international treaty designed to phase out ozone-depleting substances (CFCs)." },
    { topic: "ICT", question: "Which computer memory loses data when power is switched off?", options: ["ROM", "Hard disk", "RAM", "Flash memory"], answer_index: 2, explanation: "RAM (Random Access Memory) is volatile — its contents are lost when power is cut off." },
    { topic: "Teaching", question: "'Scaffolding' in education refers to:", options: ["Physical construction in school premises", "Temporary support to help learners achieve a task", "A rigid curriculum structure", "Evaluating student performance"], answer_index: 1, explanation: "Scaffolding (Vygotsky) involves structured support gradually withdrawn as the learner becomes more competent." },
  ],
  "December 2021": [
    { topic: "Teaching", question: "The 'Zone of Proximal Development' (ZPD) is associated with:", options: ["Jean Piaget", "B.F. Skinner", "Lev Vygotsky", "John Dewey"], answer_index: 2, explanation: "ZPD is Vygotsky's concept describing the gap between what a learner can do alone vs. with guidance." },
    { topic: "Research", question: "A 'Type I error' in research occurs when:", options: ["A true null hypothesis is incorrectly rejected", "A false null hypothesis is accepted", "Insufficient data is collected", "An invalid measurement tool is used"], answer_index: 0, explanation: "Type I error (false positive) occurs when a true null hypothesis is incorrectly rejected." },
    { topic: "Environment", question: "The Sustainable Development Goals (SDGs) were adopted by the UN in:", options: ["2012", "2013", "2015", "2017"], answer_index: 2, explanation: "The 17 SDGs were adopted by all UN member states in September 2015 as part of the 2030 Agenda for Sustainable Development." },
    { topic: "ICT", question: "A computer virus is:", options: ["A hardware malfunction", "A malicious program that can replicate and harm computer systems", "A type of antivirus software", "A networking protocol"], answer_index: 1, explanation: "A computer virus is malicious software that can self-replicate, spread, and cause damage to systems." },
    { topic: "Research", question: "'Reliability' of a research instrument means:", options: ["It measures what it is supposed to measure", "It gives consistent results across repeated measurements", "It is easy to administer", "It is approved by experts"], answer_index: 1, explanation: "Reliability refers to the consistency and repeatability of a measurement instrument." },
    { topic: "Teaching", question: "The word 'curriculum' is literally derived from a Latin word meaning:", options: ["Course of study", "A running track / race course", "Knowledge and skills", "Educational programme"], answer_index: 1, explanation: "'Curriculum' derives from the Latin 'currere' meaning 'to run' or 'a running track'." },
    { topic: "Maths", question: "In a class of 40 students, 60% failed in English. How many passed?", options: ["10", "16", "24", "25"], answer_index: 1, explanation: "60% failed → 40% passed. 40% of 40 = 16 students." },
    { topic: "Research", question: "Which is a characteristic of good research?", options: ["Based on unverified assumptions", "Relies on authority rather than evidence", "Systematic, empirical, and objective", "Focuses on confirming existing beliefs"], answer_index: 2, explanation: "Good research is systematic (follows a plan), empirical (based on observable evidence), and objective (free from personal bias)." },
    { topic: "Reasoning", question: "'Lateral thinking' as a problem-solving approach is associated with:", options: ["Abraham Maslow", "Edward de Bono", "Albert Bandura", "Carl Rogers"], answer_index: 1, explanation: "Edward de Bono introduced 'lateral thinking' — solving problems through indirect and creative approaches." },
    { topic: "Environment", question: "Which of the following is NOT an air pollutant?", options: ["Sulphur dioxide (SO₂)", "Nitrogen dioxide (NO₂)", "Oxygen (O₂)", "Carbon monoxide (CO)"], answer_index: 2, explanation: "Oxygen is essential for life and is not a pollutant. SO₂, NO₂, and CO are harmful air pollutants." },
  ],
  "June 2021": [
    { topic: "Teaching", question: "The teaching principle of proceeding from known to unknown means:", options: ["Use correlation across subjects", "Build on students' existing knowledge to introduce new concepts", "Revise frequently", "Generate student interest first"], answer_index: 1, explanation: "This principle suggests using what students already know as a foundation to introduce new concepts effectively." },
    { topic: "Research", question: "Which research design is used to establish cause-and-effect relationships?", options: ["Descriptive research", "Correlational research", "Experimental research", "Historical research"], answer_index: 2, explanation: "Experimental research manipulates independent variables to determine their causal effect on dependent variables." },
    { topic: "Reasoning", question: "The 'butterfly effect' is related to which theory?", options: ["Quantum theory", "Chaos theory", "Relativity theory", "String theory"], answer_index: 1, explanation: "The butterfly effect is a concept in chaos theory suggesting small changes can have large, unpredictable consequences." },
    { topic: "Education", question: "Which is NOT a function of the UGC?", options: ["Allocating grants to universities", "Setting standards of higher education", "Directly running government schools", "Advising Central and State Governments on higher education"], answer_index: 2, explanation: "UGC deals with higher education (universities/colleges), not government schools, which are managed by state departments." },
    { topic: "ICT", question: "The decimal equivalent of binary number 1011 is:", options: ["9", "10", "11", "13"], answer_index: 2, explanation: "1011 in binary = 1×8 + 0×4 + 1×2 + 1×1 = 8+0+2+1 = 11." },
    { topic: "Research", question: "Which sampling technique gives every member of the population an equal chance of selection?", options: ["Purposive sampling", "Snowball sampling", "Simple random sampling", "Convenience sampling"], answer_index: 2, explanation: "Simple random sampling ensures each member has an equal and independent chance of being selected." },
    { topic: "Environment", question: "The most significant ozone hole is predominantly located over:", options: ["The Arctic region", "The Antarctic region", "The equatorial region", "The temperate zones"], answer_index: 1, explanation: "The most significant ozone hole has been observed over Antarctica, primarily during spring months." },
    { topic: "Teaching", question: "When students brainstorm solutions to a problem, which level of Bloom's Taxonomy is addressed?", options: ["Remembering", "Understanding", "Applying", "Creating"], answer_index: 3, explanation: "Brainstorming to generate new solutions falls under 'Creating' — the highest level in Bloom's revised taxonomy." },
    { topic: "Research", question: "Which statement about correlation is correct?", options: ["Correlation always implies causation", "Correlation measures the direction and strength of a linear relationship", "A correlation of 0 means absolutely no relationship", "Correlation can only be positive"], answer_index: 1, explanation: "Correlation measures strength and direction of a linear relationship between two variables — it does NOT imply causation." },
    { topic: "Communication", question: "Which type of communication flows from employees to management?", options: ["Downward communication", "Upward communication", "Lateral communication", "Diagonal communication"], answer_index: 1, explanation: "Upward communication flows from subordinates to superiors — e.g., feedback, reports, grievances." },
  ],
};

// ---- Mock test sets ----
export const MOCK: Record<string, SeedQuestion[]> = {
  "UGC NET Education — Dec 2025 (Shift 2)": UGCNET_DEC2025,
  "Mock Test 1": [
    { topic: "Teaching", question: "Which teaching method is most suitable for a large class with limited time?", options: ["Project method", "Lecture method", "Discussion method", "Seminar method"], answer_index: 1, explanation: "The lecture method allows the teacher to cover content efficiently with a large group in limited time." },
    { topic: "Research", question: "A research variable that the researcher manipulates is called:", options: ["Dependent variable", "Controlled variable", "Independent variable", "Intervening variable"], answer_index: 2, explanation: "The independent variable is the one the researcher changes to observe its effect on the dependent variable." },
    { topic: "Communication", question: "The process by which a receiver interprets a message is called:", options: ["Encoding", "Decoding", "Feedback", "Transmission"], answer_index: 1, explanation: "Decoding is the process by which the receiver interprets and makes sense of the encoded message." },
    { topic: "Maths", question: "Which number is both a perfect square and a perfect cube?", options: ["8", "16", "27", "64"], answer_index: 3, explanation: "64 = 8² (perfect square) and 64 = 4³ (perfect cube). Hence 64 satisfies both." },
    { topic: "ICT", question: "E-learning is primarily associated with:", options: ["Traditional classroom teaching", "Learning using electronic technology and internet", "Experimental learning in labs", "Exchange learning between countries"], answer_index: 1, explanation: "E-learning refers to learning facilitated by electronic technologies, particularly the internet." },
    { topic: "Environment", question: "The MOST serious environmental problem associated with burning fossil fuels is:", options: ["Noise pollution", "Water contamination", "Climate change due to greenhouse gas emissions", "Soil erosion"], answer_index: 2, explanation: "Burning fossil fuels releases CO₂ and other greenhouse gases — the primary driver of climate change." },
    { topic: "Teaching", question: "A student who learns by watching others is demonstrating:", options: ["Operant conditioning", "Classical conditioning", "Observational / social learning", "Insight learning"], answer_index: 2, explanation: "Observational learning (Bandura's Social Learning Theory) occurs when individuals learn by watching and imitating others." },
    { topic: "Maths", question: "In the sequence 2, 6, 12, 20, 30, ? — the next number is:", options: ["40", "42", "44", "48"], answer_index: 1, explanation: "Differences: 4, 6, 8, 10, 12 → next difference is 12, so 30+12=42." },
    { topic: "Research", question: "'Validity' of a test best means:", options: ["The test produces consistent results", "The test measures exactly what it is intended to measure", "The test is easy to score", "The test is widely used"], answer_index: 1, explanation: "Validity refers to whether a test actually measures what it claims to measure." },
    { topic: "ICT", question: "'Digital literacy' includes the ability to:", options: ["Only type fast on a keyboard", "Only repair computers", "Effectively use digital tools and critically evaluate online information", "Only use social media"], answer_index: 2, explanation: "Digital literacy encompasses finding, evaluating, using, and creating information using digital technologies." },
    { topic: "Education", question: "Which Article of the Indian Constitution provides free and compulsory education for children aged 6–14?", options: ["Article 21", "Article 21A", "Article 45", "Article 51"], answer_index: 1, explanation: "Article 21A (86th Constitutional Amendment, 2002) makes free and compulsory education for children 6–14 a fundamental right." },
    { topic: "Research", question: "A 'literature review' in research serves to:", options: ["Prove the researcher has read many books", "Identify gaps in existing knowledge and contextualise the study", "List all books published in the field", "Replace data collection"], answer_index: 1, explanation: "A literature review surveys existing research to identify what is known and establish the rationale for a new study." },
    { topic: "Communication", question: "Which is an example of verbal communication?", options: ["Body language", "Facial expressions", "Gesture", "Written report"], answer_index: 3, explanation: "Verbal communication involves words — spoken or written. A written report uses words, hence it is verbal." },
    { topic: "Education", question: "Sarva Shiksha Abhiyan (SSA) is focused on:", options: ["Higher education reform", "Universalisation of elementary education", "Vocational training programs", "Teacher education at university level"], answer_index: 1, explanation: "SSA is a flagship programme by the Government of India for Universalisation of Elementary Education." },
    { topic: "Maths", question: "The number of times an event occurs in a dataset is called its:", options: ["Mean", "Median", "Frequency", "Range"], answer_index: 2, explanation: "Frequency is the count of how many times a particular value or event occurs in a dataset." },
    { topic: "ICT", question: "Which protocol is used to send emails over the internet?", options: ["HTTP", "FTP", "SMTP", "TCP"], answer_index: 2, explanation: "SMTP (Simple Mail Transfer Protocol) is the standard protocol for sending email messages between servers." },
    { topic: "Research", question: "Which is a non-parametric statistical test?", options: ["t-test", "ANOVA", "Chi-square test", "Pearson correlation"], answer_index: 2, explanation: "The Chi-square test is a non-parametric test that does not assume a specific data distribution." },
    { topic: "Teaching", question: "The 'Hidden Curriculum' refers to:", options: ["Secret subjects taught in schools", "Unofficial norms and values transmitted through schooling", "Online course materials not published", "Extra-curricular activities only"], answer_index: 1, explanation: "Hidden curriculum refers to implicit lessons and values students learn in school beyond the official curriculum." },
    { topic: "Environment", question: "'Acid rain' is primarily caused by atmospheric pollution from:", options: ["CO₂ and CO", "SO₂ and NOx", "O₃ and H₂O", "CH₄ and N₂"], answer_index: 1, explanation: "Acid rain is caused by SO₂ and NOx emissions that react with atmospheric moisture to form acids." },
    { topic: "Reasoning", question: "Which is an example of inductive reasoning?", options: ["All men are mortal; Socrates is a man; therefore Socrates is mortal", "This crow is black; that crow is black; therefore all crows are black", "If it rains, the ground gets wet; the ground is wet; therefore it has rained", "No conclusion can be drawn without further data"], answer_index: 1, explanation: "Inductive reasoning draws general conclusions from specific observations — generalising from observed crows to all crows." },
  ],
};
